export const homeKitchenButton ="//a[normalize-space()='Home & Kitchen']";
export const glasswareLink = "//a[normalize-space()='Glass ware']";
export const priceOutside = "//span[normalize-space()='323']";
export const product ="//span[@class='a-size-base-plus a-color-base a-text-normal'][contains(text(),'Yera Glass Mug with Handle-250ml Set of 6 Pieces M')]";
export const priceInside = "//span[normalize-space()='323']";
export const addToCartButton = "//input[@id='add-to-cart-button']";
export const cartSubTotal = "//div[@id='sw-subtotal']/descendant::span[@class='a-price sw-subtotal-amount']";
export const goToCartButton = "//a[@href='/cart?ref_=sw_gtc']";
export const glassProductCart = "//span[@class='a-truncate-cut'][contains(text(),'Yera Glass Mug with Handle-250ml Set of 6 Pieces M')]";
export const mobileProductCart = "//span[@class='a-truncate-cut'][contains(text(),'OnePlus 11R 5G (Sonic Black, 8GB RAM, 128GB Storag')]";
export const glassPriceCart = "//span[contains(text(),'Yera Glass Mug with Handle')]//ancestor::li[@class='a-spacing-mini sc-item-product-title-cont']//following-sibling::div[@class='sc-item-price-block']//descendant::span[@class='a-size-medium a-color-base sc-price sc-white-space-nowrap sc-product-price a-text-bold']";
export const mobilePriceCart ="//span[contains(text(),'OnePlus 11R 5G (Sonic Black, 8GB RAM, 128GB Storage)')]//ancestor::li[@class='a-spacing-mini sc-item-product-title-cont']//following-sibling::div[@class='sc-item-price-block']//descendant::span[@class='a-size-medium a-color-base sc-price sc-white-space-nowrap sc-product-price a-text-bold']";
